#!/bin/bash
echo "--- Security Headers (veklom.com) ---"
curl -sI https://veklom.com | grep -i "x-frame\|strict\|content-security\|referrer\|x-content\|permissions\|hsts\|x-xss\|access-control\|server\|cf-ray\|cache\|etag\|last-modified\|content-type\|status\|location"
echo "---"
echo "--- Status Codes and Content Types ---"
urls=(
    "https://veklom.com/workspace"
    "https://veklom.com/uptime"
    "https://veklom.com/docs"
    "https://veklom.com/terminal"
    "https://veklom.com/command-center"
    "https://veklom.com/api/v1/platform/pulse"
    "https://veklom.com/legal/terms"
    "https://veklom.com/legal/privacy"
    "https://veklom.com/legal/security"
    "https://veklom.com/irongrid"
    "https://veklom.com/gpc-engine"
    "https://veklom.com/api/v1/openapi.json"
    "https://veklom.com/api/v1/feedback/"
    "https://veklom.com/workspace/login"
    "https://veklom.com/og-image.png"
    "https://veklom.com/favicon.svg"
    "https://veklom.com/robots.txt"
    "https://veklom.com/sitemap.xml"
    "https://veklom.com/api/v1/platform/status-updates"
    "https://veklom.com/api/v1/gpc/stats"
    "https://veklom.com/api/v1/agents/registry"
    "https://veklom.com/api/v1/marketplace/categories"
    "https://veklom.com/api/v1/command-center/users/summary"
    "https://veklom.com/api/v1/copilot/registry"
    "https://veklom.com/api/v1/sys/health"
    "https://veklom.com/api/v1/sys/gpu"
    "https://veklom.com/api/v1/agents/monthly-report"
    "https://veklom.com/api/v1/agents/decision-frames"
    "https://veklom.com/api/v1/ai/escalation/stats"
    "https://veklom.com/api/v1/gpc/plans"
    "https://veklom.com/api/v1/workspace/overview"
    "https://veklom.com/api/v1/workspace/overview/live"
    "https://veklom.com/api/v1/auth/me"
    "https://veklom.com/api/v1/auth/eval-session"
    "https://veklom.com/api/v1/agents/hrm/audit"
    "https://veklom.com/api/v1/agents/skills"
    "https://lockerphycer.veklom.com"
    "https://veklom.dev"
)
for url in "${urls[@]}"; do
    echo -n "$url: "
    curl -sI "$url" | grep -i "content-type\|status\|location\|allow\|access-control" | tr -d '\r' | tr '\n' ';'
    echo ""
done
echo "---"
echo "--- robots.txt ---"
curl -s https://veklom.com/robots.txt
echo "---"
echo "--- sitemap.xml (first 10 lines) ---"
curl -s https://veklom.com/sitemap.xml | head -n 10
echo "---"
echo "--- OpenAPI /feedback endpoint check ---"
curl -s https://veklom.com/api/v1/openapi.json | grep -q "/feedback" && echo "/feedback endpoint found" || echo "/feedback endpoint NOT found"
echo "---"
echo "--- OpenAPI /platform/status-updates endpoint check ---"
curl -s https://veklom.com/api/v1/openapi.json | grep -q "/platform/status-updates" && echo "/platform/status-updates endpoint found" || echo "/platform/status-updates endpoint NOT found"
echo "---"
echo "--- OpenAPI total paths and tags ---"
python3 -c "import sys,json; d=json.load(sys.stdin); print('paths:',len(d.get('paths',{}))); print('tags:',[t.get('name') for t in d.get('tags',[])])" < <(curl -s https://veklom.com/api/v1/openapi.json)
echo "---"
echo "done"
