#!/bin/bash
# Manual deployment instructions for GPC Standalone to Coolify

echo "🎯 Veklom GPC Standalone Deployment Instructions"
echo "=================================================="
echo ""
echo "1. Open Coolify: http://5.78.135.11:8000/applications/new"
echo ""
echo "2. Fill in the following configuration:"
echo "   Name: veklom-gpc"
echo "   Description: Veklom GPC Black Box - Standalone Governed Plan Compiler"
echo "   Build Pack: Dockerfile"
echo "   Base Directory: /gpc-standalone"
echo "   Dockerfile Location: /Dockerfile"
echo "   Ports Exposes: 80"
echo "   Domains: https://gpc.veklom.com"
echo "   Git Repository: reprewindai-dev/veklom-byos-backend"
echo "   Git Branch: main"
echo ""
echo "3. Click 'Save' to create the application"
echo ""
echo "4. Once created, click 'Deploy' to start the deployment"
echo ""
echo "5. The GPC will be available at: https://gpc.veklom.com"
echo ""
echo "✅ Files are ready in /gpc-standalone directory:"
echo "   - index.html (Complete GPC Black Box interface)"
echo "   - Dockerfile (Nginx configuration)"
echo "   - nginx.conf (Server configuration)"
echo ""
echo "🚀 The GPC includes:"
echo "   - Live API integration with https://api.veklom.com/api/v1/gpc"
echo "   - Plan compilation with compliance frameworks"
echo "   - Probability routing simulation"
echo "   - Professional Black Box interface"
echo "   - No Render dependencies (instant loading)"
