"""Governance Engine (The Spine) for coordinating PGL execution pipelines and constitutional writes."""

import time
import uuid
import hashlib
import json
import logging
from typing import Dict, Any, List, Optional
from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from backend.core.ai.provider_router import run_completion, normalize_messages
from backend.core.services.genome_service import GenomeService
from backend.core.services.guardrail_service import guardrail_service
from backend.core.services.certificate_service import CertificateService
from backend.core.services.memory_fabric_service import MemoryFabricService
from backend.core.services.policy_registry_service import PolicyRegistryService
from backend.db.models.genome import GenomeVersion
from backend.db.models.ledger import LedgerEvent
from backend.db.models.agent import Agent

logger = logging.getLogger(__name__)


def _compute_hash(data: Any) -> str:
    """Helper to compute deterministic SHA-256 hash of any JSON-serializable data."""
    canonical_str = json.dumps(data, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(canonical_str.encode('utf-8')).hexdigest()


class GovernanceEngine:
    """The central orchestrator enforcing the 18-step PGL governance pipeline."""

    @classmethod
    async def runGovernedExecution(
        cls,
        db: AsyncSession,
        agent_id: int,
        request_body: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Executes a governed LLM completion.
        Workflow: risk scoring -> tier -> budget -> policy auth -> completion -> watchtowers -> rewrite -> ledger/evidence -> certificate.
        """
        start_time = time.time()
        trace_id = request_body.get("trace_id") or f"trace_{uuid.uuid4().hex[:8]}"

        # 1. Fetch agent and current genome
        agent_query = select(Agent).where(Agent.id == agent_id)
        agent_res = await db.execute(agent_query)
        agent = agent_res.scalar_one_or_none()
        if not agent:
            raise HTTPException(status_code=404, detail=f"Agent with ID {agent_id} not found")

        genome_query = select(GenomeVersion).where(GenomeVersion.agent_id == agent_id).order_by(GenomeVersion.version.desc())
        genome_res = await db.execute(genome_query)
        genome = genome_res.scalars().first()
        
        # Fallback to creating/resolving default genome if none exists
        if not genome:
            default_payload = {
                "model_layer": {"model": "gpt-4o-mini", "temperature": 0.7},
                "prompt_layer": {"system_prompt": "You are a helpful Veklom agent."},
                "policy_layer": {"max_tokens": 1000},
                "watchtower_layer": {"rules": []},
                "task_profile": {"task_type": "general", "budget_limit": 100}
            }
            genome = await GenomeService.resolve_or_create(db, agent_id, default_payload, "Autogenerated Default Genome")

        genome_hash = genome.merkle_root

        # 2. Risk scoring & Tier assignment
        task_type = request_body.get("task_type") or genome.payload.get("task_profile", {}).get("task_type", "general")
        org_id = request_body.get("org_id") or "default_org"
        risk_profile = await MemoryFabricService.get_org_risk_profile(db, org_id)

        # Dynamic risk calculation
        composite_risk = risk_profile.composite_risk
        if composite_risk >= 0.7 or risk_profile.injection_attempts >= 5 or task_type.lower() in ("financial", "critical", "admin"):
            tier = "T2"
        elif composite_risk >= 0.3 or task_type.lower() in ("sensitive", "moderation"):
            tier = "T1"
        else:
            tier = "T0"

        # 3. Budget arbitration (mock check)
        user_role = request_body.get("role") or "viewer"
        user_id = request_body.get("user_id") or "default_user"
        wallet_balance = 500000  # Mock balance matching wallet_guard.py
        token_cost = 50 if tier == "T2" else (30 if tier == "T1" else 15)
        if wallet_balance < token_cost:
            raise HTTPException(status_code=402, detail="Insufficient wallet tokens for requested execution tier")

        # 4. Policy Authorization
        auth_res = await PolicyRegistryService.authorize(
            db=db,
            user_id=user_id,
            org_id=org_id,
            role=user_role,
            task_type=task_type,
            tier=tier
        )
        if not auth_res["authorized"]:
            raise HTTPException(status_code=403, detail=f"Policy authorization rejected: {auth_res['reason']}")

        # 5. Build completion request and call LLM
        messages = normalize_messages(request_body)
        
        # Inject system prompt from prompt layer if present
        prompt_layer = genome.payload.get("prompt_layer") or {}
        system_prompt = prompt_layer.get("system_prompt")
        if system_prompt:
            messages.insert(0, {"role": "system", "content": system_prompt})

        completion_body = {
            **request_body,
            "messages": messages,
            "model": request_body.get("model") or genome.payload.get("model_layer", {}).get("model", "gpt-4o-mini")
        }

        # First LLM call
        completion_res = await run_completion(completion_body)
        llm_output = completion_res.payload["choices"][0]["message"]["content"]

        # 6. Run watchtowers
        task_profile = genome.payload.get("task_profile") or {}
        watchtower_results = await guardrail_service.run_watchtowers(llm_output, messages, tier, task_profile)
        
        # 7. Check tier pass rules & rewrite-once if fail
        passed = guardrail_service.check_tier_pass(watchtower_results, tier, task_profile)
        rewrite_applied = False
        
        if not passed:
            # Attempt rewrite once
            rewrite_applied = True
            corrections = guardrail_service.build_corrections(watchtower_results)
            logger.info(f"Watchtower validation failed. Attempting rewrite-once. Reasons: {corrections['reasons']}")
            
            # Append corrective instructions
            messages.append({"role": "assistant", "content": llm_output})
            messages.append({"role": "user", "content": corrections["prompt_instructions"]})
            
            # Rerun completion
            completion_body["messages"] = messages
            completion_res = await run_completion(completion_body)
            llm_output = completion_res.payload["choices"][0]["message"]["content"]
            
            # Re-evaluate
            watchtower_results = await guardrail_service.run_watchtowers(llm_output, messages, tier, task_profile)
            passed = guardrail_service.check_tier_pass(watchtower_results, tier, task_profile)
            
            if not passed:
                # Escalation block
                logger.error("Rewrite-once watchtower validation failed again. Blocking execution.")
                # Increment injection attempts in risk profile if safety/injection rule failed
                injection_failed = any(r["name"] == "injection_scan" and not r["passed"] for r in watchtower_results)
                await MemoryFabricService.record_execution(
                    db=db,
                    org_id=org_id,
                    trace_id=trace_id,
                    injection_detected=injection_failed,
                    override_applied=False,
                    task_type=task_type,
                    genome_hash=genome_hash,
                    performance_score=0.0
                )
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail={
                        "error": "Governance block: output failed watchtower validation policies after rewrite attempt",
                        "watchtower_results": watchtower_results
                    }
                )

        # 8. Record Ledger Event
        input_hash = _compute_hash(messages)
        output_hash = _compute_hash(llm_output)

        # Calculate prev_hash from last LedgerEvent
        latest_event_query = select(LedgerEvent).where(LedgerEvent.agent_id == agent_id).order_by(LedgerEvent.id.desc())
        latest_event_res = await db.execute(latest_event_query)
        latest_event = latest_event_res.scalars().first()
        prev_hash = latest_event.event_hash if latest_event else None

        event_details = {
            "trace_id": trace_id,
            "input_hash": input_hash,
            "output_hash": output_hash,
            "tier": tier,
            "rewrite_applied": rewrite_applied
        }
        event_hash = hashlib.sha256(
            (json.dumps(event_details, sort_keys=True) + (prev_hash or "")).encode('utf-8')
        ).hexdigest()

        ledger_event = LedgerEvent(
            agent_id=agent_id,
            event_id=str(uuid.uuid4()),
            event_type="governed_execution",
            actor=user_id,
            summary=f"Governed execution completed at tier {tier}",
            details=event_details,
            prev_event_hash=prev_hash,
            event_hash=event_hash,
            org_id=org_id,
            trace_id=trace_id,
            policy_version=await PolicyRegistryService.get_current_version(db),
            constitution_version="1.0.0",
            override_applied=False,
            genome_hash=genome_hash
        )
        db.add(ledger_event)

        # 9. Record Memory Fabric execution details
        injection_detected = any(r["name"] == "injection_scan" and not r["passed"] for r in watchtower_results)
        await MemoryFabricService.record_execution(
            db=db,
            org_id=org_id,
            trace_id=trace_id,
            injection_detected=injection_detected,
            override_applied=False,
            task_type=task_type,
            genome_hash=genome_hash,
            performance_score=1.0,
            output_signature=output_hash[:16]
        )

        # 10. Issue Execution Certificate
        overhead_ms = int((time.time() - start_time) * 1000)
        cert = await CertificateService.issue_execution_certificate(
            db=db,
            trace_id=trace_id,
            genome_hash=genome_hash,
            input_hash=input_hash,
            output_hash=output_hash,
            watchtower_results=watchtower_results,
            governance_tier=tier,
            governance_overhead_ms=overhead_ms,
            policy_version=ledger_event.policy_version,
            constitution_version=ledger_event.constitution_version
        )

        await db.commit()

        return {
            "trace_id": trace_id,
            "status": "completed",
            "output": llm_output,
            "governance_tier": tier,
            "rewrite_applied": rewrite_applied,
            "execution_certificate_jwt": cert.certificate_jwt,
            "governance_overhead_ms": overhead_ms
        }

    @classmethod
    async def commitConstitutionalWrite(
        cls,
        db: AsyncSession,
        agent_id: int,
        action: str,
        write_payload: Dict[str, Any],
        user_id: str,
        org_id: str,
        role: str,
        trace_id: Optional[str] = None,
        override_requested: bool = False,
        override_reason: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Executes a protected/constitutional write action.
        Validates the action against active constitutional/policy rules.
        """
        trace_id = trace_id or f"trace_{uuid.uuid4().hex[:8]}"

        # 1. Fetch agent and genome
        agent_query = select(Agent).where(Agent.id == agent_id)
        agent_res = await db.execute(agent_query)
        agent = agent_res.scalar_one_or_none()
        if not agent:
            raise HTTPException(status_code=404, detail=f"Agent with ID {agent_id} not found")

        genome_query = select(GenomeVersion).where(GenomeVersion.agent_id == agent_id).order_by(GenomeVersion.version.desc())
        genome_res = await db.execute(genome_query)
        genome = genome_res.scalars().first()
        genome_hash = genome.merkle_root if genome else "unknown"

        # 2. Constitutional policy validation
        # Allowed write actions catalog:
        allowed_actions = ["REGISTER_AGENT", "UPDATE_GENOME", "ISSUE_CERTIFICATE", "REVOKE_AGENT", "OVERRIDE_POLICY"]
        if action not in allowed_actions:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Action '{action}' is not a registered constitutional write action"
            )

        # Policy block logic: viewer is blocked from all writes
        write_blocked = (role.lower() == "viewer")
        
        # Specific rule: only admins can update genome or revoke agents
        if action in ("UPDATE_GENOME", "REVOKE_AGENT") and role.lower() not in ("admin", "super_admin"):
            write_blocked = True

        override_applied = False
        if write_blocked:
            # 3. Check override path
            if override_requested and role.lower() in ("admin", "super_admin", "operator"):
                if not override_reason:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Override requested but no override_reason provided"
                    )
                override_applied = True
                logger.warning(f"Protected write override applied for action '{action}' by user '{user_id}'")
            else:
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail=f"Protected write action '{action}' rejected: Insufficient permissions for role '{role}'"
                )

        # 4. State machine / Execution check (mock database/state transition)
        # E.g. If revoking agent, agent status must not already be revoked
        if action == "REVOKE_AGENT" and agent.status == "revoked":
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="State transition check failed: Agent is already revoked"
            )

        # Simulate execution
        if action == "REVOKE_AGENT":
            agent.status = "revoked"
        elif action == "UPDATE_GENOME":
            # Real update genome payload handled by caller, here we just acknowledge state transition
            agent.status = "updated"

        # 5. Record to Tamper-Evident Ledger
        latest_event_query = select(LedgerEvent).where(LedgerEvent.agent_id == agent_id).order_by(LedgerEvent.id.desc())
        latest_event_res = await db.execute(latest_event_query)
        latest_event = latest_event_res.scalars().first()
        prev_hash = latest_event.event_hash if latest_event else None

        event_details = {
            "action": action,
            "write_payload": write_payload,
            "override_applied": override_applied,
            "override_reason": override_reason
        }
        event_hash = hashlib.sha256(
            (json.dumps(event_details, sort_keys=True) + (prev_hash or "")).encode('utf-8')
        ).hexdigest()

        ledger_event = LedgerEvent(
            agent_id=agent_id,
            event_id=str(uuid.uuid4()),
            event_type=f"constitutional_write:{action}",
            actor=user_id,
            summary=f"Constitutional write '{action}' executed" + (" (with override)" if override_applied else ""),
            details=event_details,
            prev_event_hash=prev_hash,
            event_hash=event_hash,
            org_id=org_id,
            trace_id=trace_id,
            policy_version=await PolicyRegistryService.get_current_version(db),
            constitution_version="1.0.0",
            override_applied=override_applied,
            override_reason=override_reason,
            genome_hash=genome_hash
        )
        db.add(ledger_event)

        # 6. Update Memory Fabric risk score (increment override abuse if applied)
        await MemoryFabricService.record_execution(
            db=db,
            org_id=org_id,
            trace_id=trace_id,
            injection_detected=False,
            override_applied=override_applied,
            task_type="write",
            genome_hash=genome_hash
        )

        await db.commit()

        return {
            "trace_id": trace_id,
            "status": "committed",
            "action": action,
            "override_applied": override_applied,
            "ledger_event_id": ledger_event.event_id
        }
