"""add missing columns

Revision ID: cb82d08a68fe
Revises: 25dabdc85714
Create Date: 2026-07-18 20:23:01.625092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb82d08a68fe'
down_revision: Union[str, None] = '25dabdc85714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capability_haunt_states', sa.Column('manifest', sa.JSON(), nullable=True, server_default='{}'))
    op.add_column('vnp_regional_telemetry', sa.Column('provenance_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vnp_regional_telemetry', 'provenance_hash')
    op.drop_column('capability_haunt_states', 'manifest')
    # ### end Alembic commands ###
