"""Refactor SettlementLedger canonical model

Revision ID: d51e758d7678
Revises: 2c4090ba99cb
Create Date: 2026-06-23 18:04:20.915609

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd51e758d7678'
down_revision: Union[str, None] = '2c4090ba99cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_agent_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_agent_memory_agent_id'), 'rag_agent_memory', ['agent_id'], unique=False)
    op.create_index(op.f('ix_rag_agent_memory_id'), 'rag_agent_memory', ['id'], unique=False)
    op.create_index(op.f('ix_rag_agent_memory_tenant_id'), 'rag_agent_memory', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rag_agent_memory_workspace_id'), 'rag_agent_memory', ['workspace_id'], unique=False)
    op.create_table('rag_document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('document_classification', sa.String(), nullable=True),
    sa.Column('access_tags', sa.JSON(), nullable=True),
    sa.Column('created_by_agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_document_chunks_id'), 'rag_document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_source_document_id'), 'rag_document_chunks', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_tenant_id'), 'rag_document_chunks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rag_document_chunks_workspace_id'), 'rag_document_chunks', ['workspace_id'], unique=False)
    op.create_table('settlement_ledger',
    sa.Column('id', backend.db.models.ledger.GUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('fee_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SETTLED', 'FAILED', name='settlement_status_enum'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=128), nullable=True),
    sa.Column('authority_run_id', sa.String(length=128), nullable=True),
    sa.Column('payment_proof_id', sa.String(length=255), nullable=True),
    sa.Column('external_payment_id', sa.String(length=255), nullable=True),
    sa.Column('settlement_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_settlement_ledger_authority_run_id'), 'settlement_ledger', ['authority_run_id'], unique=False)
    op.create_index(op.f('ix_settlement_ledger_execution_id'), 'settlement_ledger', ['execution_id'], unique=False)
    op.create_index(op.f('ix_settlement_ledger_external_payment_id'), 'settlement_ledger', ['external_payment_id'], unique=False)
    op.create_index(op.f('ix_settlement_ledger_payment_proof_id'), 'settlement_ledger', ['payment_proof_id'], unique=False)
    op.create_index(op.f('ix_settlement_ledger_status'), 'settlement_ledger', ['status'], unique=False)
    op.create_index(op.f('ix_settlement_ledger_tenant_id'), 'settlement_ledger', ['tenant_id'], unique=False)
    op.create_index('ix_settlement_tenant_created', 'settlement_ledger', ['tenant_id', 'created_at'], unique=False)
    op.create_table('vnp_agent_privileges',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('revoked_by', sa.String(length=128), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.String(length=128), nullable=True),
    sa.Column('restore_reason', sa.Text(), nullable=True),
    sa.Column('last_benchmark_run_id', sa.String(length=36), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('vnp_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('provider', 'customer', 'validator', 'operator', name='tenant_type_enum'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_scope_time', 'vnp_audit_logs', ['scope_type', 'scope_id', 'created_at'], unique=False)
    op.create_table('vnp_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_mode', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_epoch_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('observed_p95', sa.Float(), nullable=False),
    sa.Column('target_p95', sa.Float(), nullable=False),
    sa.Column('penalty_applied', sa.Float(), nullable=False),
    sa.Column('new_bond_balance', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_epoch_settlements_epoch'), 'vnp_epoch_settlements', ['epoch'], unique=False)
    op.create_table('vnp_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('open', 'acknowledged', 'resolved', 'suppressed', name='incident_state_enum'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_state_opened', 'vnp_incidents', ['state', 'opened_at'], unique=False)
    op.create_table('vnp_nexus_benchmark_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('policy_adherence_score', sa.Float(), nullable=False),
    sa.Column('evidence_integrity_score', sa.Float(), nullable=False),
    sa.Column('latency_score', sa.Float(), nullable=False),
    sa.Column('cost_efficiency_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('result_state', sa.String(length=32), nullable=False),
    sa.Column('triggered_revocation', sa.Boolean(), nullable=True),
    sa.Column('evaluation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_nexus_benchmark_runs_agent_id'), 'vnp_nexus_benchmark_runs', ['agent_id'], unique=False)
    op.create_table('vnp_provider_bonds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bond_amount_usdc', sa.Float(), nullable=False),
    sa.Column('target_p95_ms', sa.Float(), nullable=False),
    sa.Column('observed_p95_ms', sa.Float(), nullable=False),
    sa.Column('sigma_ms', sa.Float(), nullable=False),
    sa.Column('deviation_ms', sa.Float(), nullable=False),
    sa.Column('tolerance_ms', sa.Float(), nullable=False),
    sa.Column('excess_ms', sa.Float(), nullable=False),
    sa.Column('penalty_usdc', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_provider_bonds_api_id'), 'vnp_provider_bonds', ['api_id'], unique=False)
    op.create_table('vnp_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vnp_stake_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('api_route', sa.String(length=128), nullable=False),
    sa.Column('stake_amount_usdc', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('sla_threshold_ms', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vnp_stake_logs_workspace_id'), 'vnp_stake_logs', ['workspace_id'], unique=False)
    op.create_table('vnp_validators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('operator_entity', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('stake_currency', sa.String(length=3), nullable=False),
    sa.Column('stake_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('active', 'suspended', 'challenged', 'retired', name='validator_state_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_verifier_nodes',
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('diversity_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('asn', sa.String(length=64), nullable=False),
    sa.Column('measurement_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('vnp_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('api_did', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('health_path', sa.String(), nullable=False),
    sa.Column('auth_scheme', sa.String(length=50), nullable=False),
    sa.Column('x402_ready', sa.Boolean(), nullable=False),
    sa.Column('pricing_model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'degraded', 'disabled', 'pending', name='api_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_did')
    )
    op.create_table('vnp_attestations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validator_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('attestation_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attestation_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('proposed', 'accepted', 'rejected', name='attestation_state_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['validator_id'], ['vnp_validators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_prepaid_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('reserved_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'currency', name='uq_vnp_prepaid_balances_cust_cur')
    )
    op.create_table('vnp_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', 'environment', name='uq_vnp_projects_cust_name_env')
    )
    op.create_table('vnp_route_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('minimum_trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allowed_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_provider_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failover_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_api_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'region_code', name='uq_vnp_api_regions_api_region')
    )
    op.create_index('idx_api_regions_lookup', 'vnp_api_regions', ['api_id', 'region_code'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('vnp_probe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('worker_region', sa.String(length=50), nullable=False),
    sa.Column('runtime', sa.String(length=50), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('api_region_code', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dns_ms', sa.Integer(), nullable=True),
    sa.Column('connect_ms', sa.Integer(), nullable=True),
    sa.Column('tls_ms', sa.Integer(), nullable=True),
    sa.Column('ttfb_ms', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('result_state', sa.Enum('success', 'timeout', 'http_error', 'transport_error', 'dns_error', 'tls_error', name='probe_result_state_enum'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timeout', sa.Boolean(), nullable=False),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('signature_alg', sa.String(length=20), nullable=False),
    sa.Column('signature_key_id', sa.String(length=100), nullable=False),
    sa.Column('signature_value', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_probe_events_api_region_time', 'vnp_probe_events', ['api_id', 'api_region_code', 'occurred_at'], unique=False)
    op.create_table('vnp_regional_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('uptime_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('throughput_rps', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regional_telemetry_region_score', 'vnp_regional_telemetry', ['region_code', 'trust_score', 'p99_latency_ms'], unique=False)
    op.create_table('vnp_route_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('requested_region', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['vnp_route_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_snapshots_generated_at', 'vnp_route_snapshots', ['generated_at'], unique=False)
    op.create_table('vnp_sdk_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['vnp_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnp_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_region', sa.String(length=50), nullable=False),
    sa.Column('sdk_region', sa.String(length=50), nullable=True),
    sa.Column('route_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('billable_units', sa.BigInteger(), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failover_count', sa.Integer(), nullable=False),
    sa.Column('preauth_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('final_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_alg', sa.String(length=20), nullable=False),
    sa.Column('signature_key_id', sa.String(length=100), nullable=False),
    sa.Column('signature_value', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['vnp_apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['vnp_sdk_credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['vnp_route_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['vnp_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_snapshot_id'], ['vnp_route_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_usage_events_customer_time', 'vnp_usage_events', ['customer_id', 'occurred_at'], unique=False)
    op.create_index('idx_usage_events_project_time', 'vnp_usage_events', ['project_id', 'occurred_at'], unique=False)
    op.create_table('vnp_settlement_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('usage_event_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Enum('credit', 'debit', 'hold', 'release', 'refund', 'adjustment', 'slash', 'reward', name='ledger_entry_type_enum'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.Enum('pending', 'posted', 'failed', 'reversed', name='settlement_state_enum'), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['vnp_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['vnp_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usage_event_id'], ['vnp_usage_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settlement_entries_customer_time', 'vnp_settlement_entries', ['customer_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_vendors_user_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('authority_decisions')
    op.drop_index(op.f('ix_high_performer_entries_genome_hash'), table_name='high_performer_entries')
    op.drop_index(op.f('ix_high_performer_entries_task_type'), table_name='high_performer_entries')
    op.drop_table('high_performer_entries')
    op.drop_index(op.f('ix_org_risk_profiles_org_id'), table_name='org_risk_profiles')
    op.drop_table('org_risk_profiles')
    op.drop_index(op.f('ix_marketplace_listings_vendor_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_agentic_checkout_sessions_order_id'), table_name='agentic_checkout_sessions')
    op.drop_index(op.f('ix_agentic_checkout_sessions_status'), table_name='agentic_checkout_sessions')
    op.drop_index(op.f('ix_agentic_checkout_sessions_workspace_id'), table_name='agentic_checkout_sessions')
    op.drop_table('agentic_checkout_sessions')
    op.drop_index(op.f('ix_memory_entries_agent_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_authority_run_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_evidence_pack_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_memory_entry_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_workspace_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_evidence_packs_agent_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_authority_run_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_creator_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_evidence_pack_id'), table_name='evidence_packs')
    op.drop_index(op.f('ix_evidence_packs_workspace_id'), table_name='evidence_packs')
    op.drop_table('evidence_packs')
    op.drop_index(op.f('ix_knowledge_templates_template_id'), table_name='knowledge_templates')
    op.drop_index(op.f('ix_knowledge_templates_workspace_id'), table_name='knowledge_templates')
    op.drop_table('knowledge_templates')
    op.drop_index(op.f('ix_browser_actions_agent_id'), table_name='browser_actions')
    op.drop_index(op.f('ix_browser_actions_authority_run_id'), table_name='browser_actions')
    op.drop_index(op.f('ix_browser_actions_browser_action_id'), table_name='browser_actions')
    op.drop_index(op.f('ix_browser_actions_evidence_pack_id'), table_name='browser_actions')
    op.drop_index(op.f('ix_browser_actions_workspace_id'), table_name='browser_actions')
    op.drop_table('browser_actions')
    op.drop_index(op.f('ix_policy_versions_version'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_knowledge_sources_source_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_workspace_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_outcome_feedback_trace_id'), table_name='outcome_feedback')
    op.drop_table('outcome_feedback')
    op.drop_index(op.f('ix_agent_identities_tenant_id'), table_name='agent_identities')
    op.drop_table('agent_identities')
    op.drop_index(op.f('ix_installed_assets_listing_id'), table_name='installed_assets')
    op.drop_index(op.f('ix_installed_assets_workspace_id'), table_name='installed_assets')
    op.drop_table('installed_assets')
    op.drop_index(op.f('ix_authority_runs_agent_id'), table_name='authority_runs')
    op.drop_index(op.f('ix_authority_runs_executor_id'), table_name='authority_runs')
    op.drop_index(op.f('ix_authority_runs_workspace_id'), table_name='authority_runs')
    op.drop_table('authority_runs')
    op.drop_index(op.f('ix_enforcement_bundles_bundle_hash'), table_name='enforcement_bundles')
    op.drop_table('enforcement_bundles')
    op.drop_index(op.f('ix_authority_bundles_creator_id'), table_name='authority_bundles')
    op.drop_index(op.f('ix_authority_bundles_workspace_id'), table_name='authority_bundles')
    op.drop_table('authority_bundles')
    op.drop_index(op.f('ix_knowledge_chunks_chunk_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_indexed_by'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_execution_certificates_genome_hash'), table_name='execution_certificates')
    op.drop_index(op.f('ix_execution_certificates_trace_id'), table_name='execution_certificates')
    op.drop_table('execution_certificates')
    op.add_column('birth_certificates', sa.Column('pgl_identity_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_birth_certificates_pgl_identity_id'), 'birth_certificates', ['pgl_identity_id'], unique=False)
    op.create_foreign_key(None, 'birth_certificates', 'pgl_identities', ['pgl_identity_id'], ['id'])
    op.add_column('execution_logs', sa.Column('evidence_pack_id', sa.String(length=36), nullable=True))
    op.add_column('execution_logs', sa.Column('data_tier', sa.Enum('bronze', 'silver', 'gold', 'unrated', name='data_tier_enum'), nullable=True))
    op.add_column('execution_logs', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('execution_logs', sa.Column('tier_score', sa.Float(), nullable=True))
    op.add_column('execution_logs', sa.Column('policy_passed', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('schema_passed', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('quality_passed', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('evidence_complete', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('runtime_error', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('security_anomaly', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('budget_exceeded', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('route_family', sa.String(length=128), nullable=True))
    op.add_column('execution_logs', sa.Column('dedupe_key', sa.String(length=128), nullable=True))
    op.add_column('execution_logs', sa.Column('tier_reason_codes', sa.JSON(), nullable=True))
    op.add_column('execution_logs', sa.Column('tiered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('execution_logs', sa.Column('eligible_for_training', sa.Boolean(), nullable=True))
    op.add_column('execution_logs', sa.Column('training_locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_exec_log_dedupe_key', 'execution_logs', ['dedupe_key'], unique=False)
    op.create_index('idx_exec_log_gold_training', 'execution_logs', ['workspace_id', 'data_tier', 'eligible_for_training', 'training_locked_at', 'created_at'], unique=False)
    op.create_index('idx_exec_log_tier_created_at', 'execution_logs', ['data_tier', 'created_at'], unique=False)
    op.create_index('idx_exec_log_ws_tier_created', 'execution_logs', ['workspace_id', 'data_tier', 'created_at'], unique=False)
    op.create_index('ix_exec_logs_workspace_provider', 'execution_logs', ['workspace_id', 'provider'], unique=False)
    op.create_index('ix_execution_logs_created_at', 'execution_logs', ['created_at'], unique=False)
    op.create_index('ix_execution_logs_data_tier', 'execution_logs', ['workspace_id', 'data_tier'], unique=False)
    op.create_index(op.f('ix_execution_logs_evidence_pack_id'), 'execution_logs', ['evidence_pack_id'], unique=False)
    op.create_index(op.f('ix_execution_logs_route_family'), 'execution_logs', ['route_family'], unique=False)
    op.create_unique_constraint('uniq_ws_dedupe_key', 'execution_logs', ['workspace_id', 'dedupe_key'])
    op.add_column('genome_versions', sa.Column('pgl_identity_id', sa.String(length=36), nullable=False))
    op.add_column('genome_versions', sa.Column('model_layer_hash', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('prompt_layer_hash', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('policy_layer_hash', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('watchtower_layer_hash', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('task_profile_hash', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('merkle_root', sa.String(length=128), nullable=True))
    op.add_column('genome_versions', sa.Column('parent_genome_ids', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_genome_versions_pgl_identity_id'), 'genome_versions', ['pgl_identity_id'], unique=False)
    op.create_unique_constraint(None, 'genome_versions', ['merkle_root'])
    op.create_foreign_key(None, 'genome_versions', 'pgl_identities', ['pgl_identity_id'], ['id'])
    op.add_column('ledger_events', sa.Column('org_id', sa.String(length=64), nullable=True))
    op.add_column('ledger_events', sa.Column('trace_id', sa.String(length=64), nullable=True))
    op.add_column('ledger_events', sa.Column('policy_version', sa.String(length=32), nullable=True))
    op.add_column('ledger_events', sa.Column('constitution_version', sa.String(length=32), nullable=True))
    op.add_column('ledger_events', sa.Column('override_applied', sa.Boolean(), nullable=False))
    op.add_column('ledger_events', sa.Column('override_reason', sa.String(length=512), nullable=True))
    op.add_column('ledger_events', sa.Column('genome_hash', sa.String(length=128), nullable=True))
    op.add_column('lineage_edges', sa.Column('parent_pgl_id', sa.String(length=36), nullable=False))
    op.add_column('lineage_edges', sa.Column('child_pgl_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_lineage_edges_child_pgl_id'), 'lineage_edges', ['child_pgl_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_parent_pgl_id'), 'lineage_edges', ['parent_pgl_id'], unique=False)
    op.create_foreign_key(None, 'lineage_edges', 'pgl_identities', ['parent_pgl_id'], ['id'])
    op.create_foreign_key(None, 'lineage_edges', 'pgl_identities', ['child_pgl_id'], ['id'])
    op.create_unique_constraint(None, 'orders', ['order_id'])
    op.add_column('pgl_certificates', sa.Column('pgl_identity_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_pgl_certificates_pgl_identity_id'), 'pgl_certificates', ['pgl_identity_id'], unique=False)
    op.create_foreign_key(None, 'pgl_certificates', 'pgl_identities', ['pgl_identity_id'], ['id'])
    op.add_column('pgl_ledger_events', sa.Column('pgl_identity_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_pgl_ledger_events_pgl_identity_id'), 'pgl_ledger_events', ['pgl_identity_id'], unique=False)
    op.create_foreign_key(None, 'pgl_ledger_events', 'pgl_identities', ['pgl_identity_id'], ['id'])
    op.alter_column('veklom_runs', 'status',
               existing_type=postgresql.ENUM('INTENT_CAPTURED', 'COMPILED', 'CONTEXTUALIZED', 'GOVERNED', 'HELD', 'APPROVED', 'DENIED', 'COMMITTED', 'ROUTED', 'EXECUTING', 'ATTESTED', 'BILLED', 'SEALED', 'FAILED', 'ROLLED_BACK', name='veklomrunstatus'),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('veklom_runs', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('INTENT_CAPTURED', 'COMPILED', 'CONTEXTUALIZED', 'GOVERNED', 'HELD', 'APPROVED', 'DENIED', 'COMMITTED', 'ROUTED', 'EXECUTING', 'ATTESTED', 'BILLED', 'SEALED', 'FAILED', 'ROLLED_BACK', name='veklomrunstatus'),
               existing_nullable=False)
    op.drop_constraint(None, 'pgl_ledger_events', type_='foreignkey')
    op.drop_index(op.f('ix_pgl_ledger_events_pgl_identity_id'), table_name='pgl_ledger_events')
    op.drop_column('pgl_ledger_events', 'pgl_identity_id')
    op.drop_constraint(None, 'pgl_certificates', type_='foreignkey')
    op.drop_index(op.f('ix_pgl_certificates_pgl_identity_id'), table_name='pgl_certificates')
    op.drop_column('pgl_certificates', 'pgl_identity_id')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'lineage_edges', type_='foreignkey')
    op.drop_constraint(None, 'lineage_edges', type_='foreignkey')
    op.drop_index(op.f('ix_lineage_edges_parent_pgl_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_child_pgl_id'), table_name='lineage_edges')
    op.drop_column('lineage_edges', 'child_pgl_id')
    op.drop_column('lineage_edges', 'parent_pgl_id')
    op.drop_column('ledger_events', 'genome_hash')
    op.drop_column('ledger_events', 'override_reason')
    op.drop_column('ledger_events', 'override_applied')
    op.drop_column('ledger_events', 'constitution_version')
    op.drop_column('ledger_events', 'policy_version')
    op.drop_column('ledger_events', 'trace_id')
    op.drop_column('ledger_events', 'org_id')
    op.drop_constraint(None, 'genome_versions', type_='foreignkey')
    op.drop_constraint(None, 'genome_versions', type_='unique')
    op.drop_index(op.f('ix_genome_versions_pgl_identity_id'), table_name='genome_versions')
    op.drop_column('genome_versions', 'parent_genome_ids')
    op.drop_column('genome_versions', 'merkle_root')
    op.drop_column('genome_versions', 'task_profile_hash')
    op.drop_column('genome_versions', 'watchtower_layer_hash')
    op.drop_column('genome_versions', 'policy_layer_hash')
    op.drop_column('genome_versions', 'prompt_layer_hash')
    op.drop_column('genome_versions', 'model_layer_hash')
    op.drop_column('genome_versions', 'pgl_identity_id')
    op.drop_constraint('uniq_ws_dedupe_key', 'execution_logs', type_='unique')
    op.drop_index(op.f('ix_execution_logs_route_family'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_evidence_pack_id'), table_name='execution_logs')
    op.drop_index('ix_execution_logs_data_tier', table_name='execution_logs')
    op.drop_index('ix_execution_logs_created_at', table_name='execution_logs')
    op.drop_index('ix_exec_logs_workspace_provider', table_name='execution_logs')
    op.drop_index('idx_exec_log_ws_tier_created', table_name='execution_logs')
    op.drop_index('idx_exec_log_tier_created_at', table_name='execution_logs')
    op.drop_index('idx_exec_log_gold_training', table_name='execution_logs')
    op.drop_index('idx_exec_log_dedupe_key', table_name='execution_logs')
    op.drop_column('execution_logs', 'training_locked_at')
    op.drop_column('execution_logs', 'eligible_for_training')
    op.drop_column('execution_logs', 'tiered_at')
    op.drop_column('execution_logs', 'tier_reason_codes')
    op.drop_column('execution_logs', 'dedupe_key')
    op.drop_column('execution_logs', 'route_family')
    op.drop_column('execution_logs', 'budget_exceeded')
    op.drop_column('execution_logs', 'security_anomaly')
    op.drop_column('execution_logs', 'runtime_error')
    op.drop_column('execution_logs', 'evidence_complete')
    op.drop_column('execution_logs', 'quality_passed')
    op.drop_column('execution_logs', 'schema_passed')
    op.drop_column('execution_logs', 'policy_passed')
    op.drop_column('execution_logs', 'tier_score')
    op.drop_column('execution_logs', 'confidence_score')
    op.drop_column('execution_logs', 'data_tier')
    op.drop_column('execution_logs', 'evidence_pack_id')
    op.drop_constraint(None, 'birth_certificates', type_='foreignkey')
    op.drop_index(op.f('ix_birth_certificates_pgl_identity_id'), table_name='birth_certificates')
    op.drop_column('birth_certificates', 'pgl_identity_id')
    op.create_table('execution_certificates',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('genome_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('input_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('output_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('watchtower_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('governance_tier', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('governance_overhead_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('policy_version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('constitution_version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('certificate_jwt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('execution_certificates_pkey'))
    )
    op.create_index(op.f('ix_execution_certificates_trace_id'), 'execution_certificates', ['trace_id'], unique=True)
    op.create_index(op.f('ix_execution_certificates_genome_hash'), 'execution_certificates', ['genome_hash'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('indexed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('indexed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_chunks_pkey'))
    )
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_indexed_by'), 'knowledge_chunks', ['indexed_by'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_chunk_id'), 'knowledge_chunks', ['chunk_id'], unique=True)
    op.create_table('authority_bundles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tool_permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workspace_restrictions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_restrictions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('prev_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='authority_bundles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_authority_bundles_workspace_id'), 'authority_bundles', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_authority_bundles_creator_id'), 'authority_bundles', ['creator_id'], unique=False)
    op.create_table('enforcement_bundles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('constitution_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('bundle_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('regression_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('compiled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('enforcement_bundles_pkey'))
    )
    op.create_index(op.f('ix_enforcement_bundles_bundle_hash'), 'enforcement_bundles', ['bundle_hash'], unique=True)
    op.create_table('authority_runs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authority_bundle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('executor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decisions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('violations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('approvals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seked_state_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('seked_policy_applied', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('seked_initial_measurement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seked_final_directive', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('evidence_pack_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('memory_entries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_actions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_actions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('denied_actions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('violation_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authority_bundle_id'], ['authority_bundles.id'], name='authority_runs_authority_bundle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='authority_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_authority_runs_workspace_id'), 'authority_runs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_authority_runs_executor_id'), 'authority_runs', ['executor_id'], unique=False)
    op.create_index(op.f('ix_authority_runs_agent_id'), 'authority_runs', ['agent_id'], unique=False)
    op.create_table('installed_assets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('installed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('installed_assets_pkey'))
    )
    op.create_index(op.f('ix_installed_assets_workspace_id'), 'installed_assets', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_installed_assets_listing_id'), 'installed_assets', ['listing_id'], unique=False)
    op.create_table('agent_identities',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_by_pgl_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_identities_pkey'))
    )
    op.create_index(op.f('ix_agent_identities_tenant_id'), 'agent_identities', ['tenant_id'], unique=False)
    op.create_table('outcome_feedback',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actual_outcome', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('predicted_outcome', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('outcome_feedback_pkey'))
    )
    op.create_index(op.f('ix_outcome_feedback_trace_id'), 'outcome_feedback', ['trace_id'], unique=True)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('source_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_indexed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_indexed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allowed_agents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_sources_pkey'))
    )
    op.create_index(op.f('ix_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_source_id'), 'knowledge_sources', ['source_id'], unique=True)
    op.create_table('policy_versions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('policies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('policy_versions_pkey'))
    )
    op.create_index(op.f('ix_policy_versions_version'), 'policy_versions', ['version'], unique=True)
    op.create_table('browser_actions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('browser_action_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authority_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('evidence_pack_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('target_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('selector', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authority_run_id'], ['authority_runs.id'], name=op.f('browser_actions_authority_run_id_fkey')),
    sa.ForeignKeyConstraint(['evidence_pack_id'], ['evidence_packs.id'], name=op.f('browser_actions_evidence_pack_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('browser_actions_pkey'))
    )
    op.create_index(op.f('ix_browser_actions_workspace_id'), 'browser_actions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_browser_actions_evidence_pack_id'), 'browser_actions', ['evidence_pack_id'], unique=False)
    op.create_index(op.f('ix_browser_actions_browser_action_id'), 'browser_actions', ['browser_action_id'], unique=True)
    op.create_index(op.f('ix_browser_actions_authority_run_id'), 'browser_actions', ['authority_run_id'], unique=False)
    op.create_index(op.f('ix_browser_actions_agent_id'), 'browser_actions', ['agent_id'], unique=False)
    op.create_table('knowledge_templates',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chunking_strategy', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_overlap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_templates_pkey'))
    )
    op.create_index(op.f('ix_knowledge_templates_workspace_id'), 'knowledge_templates', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_knowledge_templates_template_id'), 'knowledge_templates', ['template_id'], unique=True)
    op.create_table('evidence_packs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('evidence_pack_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('authority_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('artifacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hashes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verification', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pack_version', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('pack_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('prev_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authority_run_id'], ['authority_runs.id'], name='evidence_packs_authority_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evidence_packs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_evidence_packs_workspace_id'), 'evidence_packs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_evidence_packs_evidence_pack_id'), 'evidence_packs', ['evidence_pack_id'], unique=True)
    op.create_index(op.f('ix_evidence_packs_creator_id'), 'evidence_packs', ['creator_id'], unique=False)
    op.create_index(op.f('ix_evidence_packs_authority_run_id'), 'evidence_packs', ['authority_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_packs_agent_id'), 'evidence_packs', ['agent_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('memory_entry_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authority_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('evidence_pack_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ttl_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authority_run_id'], ['authority_runs.id'], name=op.f('memory_entries_authority_run_id_fkey')),
    sa.ForeignKeyConstraint(['evidence_pack_id'], ['evidence_packs.id'], name=op.f('memory_entries_evidence_pack_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_entries_pkey'))
    )
    op.create_index(op.f('ix_memory_entries_workspace_id'), 'memory_entries', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_memory_entry_id'), 'memory_entries', ['memory_entry_id'], unique=True)
    op.create_index(op.f('ix_memory_entries_evidence_pack_id'), 'memory_entries', ['evidence_pack_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_authority_run_id'), 'memory_entries', ['authority_run_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_agent_id'), 'memory_entries', ['agent_id'], unique=False)
    op.create_table('agentic_checkout_sessions',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('buyer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('amount_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_intent_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('data_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agentic_checkout_sessions_pkey'))
    )
    op.create_index(op.f('ix_agentic_checkout_sessions_workspace_id'), 'agentic_checkout_sessions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_agentic_checkout_sessions_status'), 'agentic_checkout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_agentic_checkout_sessions_order_id'), 'agentic_checkout_sessions', ['order_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pricing_model', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inventory_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inventory_sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inventory_reserved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inventory_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('version_identifier', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('marketplace_listings_pkey'))
    )
    op.create_index(op.f('ix_marketplace_listings_vendor_id'), 'marketplace_listings', ['vendor_id'], unique=False)
    op.create_table('org_risk_profiles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('abuse_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('override_abuse_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payment_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('injection_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composite_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('org_risk_profiles_pkey'))
    )
    op.create_index(op.f('ix_org_risk_profiles_org_id'), 'org_risk_profiles', ['org_id'], unique=True)
    op.create_table('high_performer_entries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('output_signature', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('performance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('genome_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('high_performer_entries_pkey'))
    )
    op.create_index(op.f('ix_high_performer_entries_task_type'), 'high_performer_entries', ['task_type'], unique=False)
    op.create_index(op.f('ix_high_performer_entries_genome_hash'), 'high_performer_entries', ['genome_hash'], unique=False)
    op.create_table('authority_decisions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authority_run_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('tool_parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('seked_measurement', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seked_ratios', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seked_directive', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seked_policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('seked_proof_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('agent_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workspace_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risk_assessment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('decision_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('execution_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('evidence_refs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hash_chain', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['authority_run_id'], ['authority_runs.id'], name=op.f('authority_decisions_authority_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('authority_decisions_pkey'))
    )
    op.create_table('vendors',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('onboarding_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vendors_pkey'))
    )
    op.create_index(op.f('ix_vendors_user_id'), 'vendors', ['user_id'], unique=False)
    op.drop_index('idx_settlement_entries_customer_time', table_name='vnp_settlement_entries')
    op.drop_table('vnp_settlement_entries')
    op.drop_index('idx_usage_events_project_time', table_name='vnp_usage_events')
    op.drop_index('idx_usage_events_customer_time', table_name='vnp_usage_events')
    op.drop_table('vnp_usage_events')
    op.drop_table('vnp_sdk_credentials')
    op.drop_index('idx_route_snapshots_generated_at', table_name='vnp_route_snapshots')
    op.drop_table('vnp_route_snapshots')
    op.drop_index('idx_regional_telemetry_region_score', table_name='vnp_regional_telemetry')
    op.drop_table('vnp_regional_telemetry')
    op.drop_index('idx_probe_events_api_region_time', table_name='vnp_probe_events')
    op.drop_table('vnp_probe_events')
    op.drop_index('idx_api_regions_lookup', table_name='vnp_api_regions', postgresql_where=sa.text('active = true'))
    op.drop_table('vnp_api_regions')
    op.drop_table('vnp_route_policies')
    op.drop_table('vnp_projects')
    op.drop_table('vnp_prepaid_balances')
    op.drop_table('vnp_attestations')
    op.drop_table('vnp_apis')
    op.drop_table('vnp_verifier_nodes')
    op.drop_table('vnp_validators')
    op.drop_index(op.f('ix_vnp_stake_logs_workspace_id'), table_name='vnp_stake_logs')
    op.drop_table('vnp_stake_logs')
    op.drop_table('vnp_providers')
    op.drop_index(op.f('ix_vnp_provider_bonds_api_id'), table_name='vnp_provider_bonds')
    op.drop_table('vnp_provider_bonds')
    op.drop_index(op.f('ix_vnp_nexus_benchmark_runs_agent_id'), table_name='vnp_nexus_benchmark_runs')
    op.drop_table('vnp_nexus_benchmark_runs')
    op.drop_index('idx_incidents_state_opened', table_name='vnp_incidents')
    op.drop_table('vnp_incidents')
    op.drop_index(op.f('ix_vnp_epoch_settlements_epoch'), table_name='vnp_epoch_settlements')
    op.drop_table('vnp_epoch_settlements')
    op.drop_table('vnp_customers')
    op.drop_index('idx_audit_logs_scope_time', table_name='vnp_audit_logs')
    op.drop_table('vnp_audit_logs')
    op.drop_table('vnp_agent_privileges')
    op.drop_index('ix_settlement_tenant_created', table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_tenant_id'), table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_status'), table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_payment_proof_id'), table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_external_payment_id'), table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_execution_id'), table_name='settlement_ledger')
    op.drop_index(op.f('ix_settlement_ledger_authority_run_id'), table_name='settlement_ledger')
    op.drop_table('settlement_ledger')
    op.drop_index(op.f('ix_rag_document_chunks_workspace_id'), table_name='rag_document_chunks')
    op.drop_index(op.f('ix_rag_document_chunks_tenant_id'), table_name='rag_document_chunks')
    op.drop_index(op.f('ix_rag_document_chunks_source_document_id'), table_name='rag_document_chunks')
    op.drop_index(op.f('ix_rag_document_chunks_id'), table_name='rag_document_chunks')
    op.drop_table('rag_document_chunks')
    op.drop_index(op.f('ix_rag_agent_memory_workspace_id'), table_name='rag_agent_memory')
    op.drop_index(op.f('ix_rag_agent_memory_tenant_id'), table_name='rag_agent_memory')
    op.drop_index(op.f('ix_rag_agent_memory_id'), table_name='rag_agent_memory')
    op.drop_index(op.f('ix_rag_agent_memory_agent_id'), table_name='rag_agent_memory')
    op.drop_table('rag_agent_memory')
    # ### end Alembic commands ###
