"""Add GPC Audit models

Revision ID: 25dabdc85714
Revises: 4a6c552e87de
Create Date: 2026-07-14 10:06:55.643568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25dabdc85714'
down_revision: Union[str, None] = '4a6c552e87de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpc_audit',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('node_index', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('data_residency_region', sa.String(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.Column('compliance_checks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_gpc_audit_tenant_id'), 'gpc_audit', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gpc_audit_pipeline_id'), 'gpc_audit', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_gpc_audit_user_id'), 'gpc_audit', ['user_id'], unique=False)
    op.create_index(op.f('ix_gpc_audit_created_at'), 'gpc_audit', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpc_audit_created_at'), table_name='gpc_audit')
    op.drop_index(op.f('ix_gpc_audit_user_id'), table_name='gpc_audit')
    op.drop_index(op.f('ix_gpc_audit_pipeline_id'), table_name='gpc_audit')
    op.drop_index(op.f('ix_gpc_audit_tenant_id'), table_name='gpc_audit')
    op.drop_table('gpc_audit')
    # ### end Alembic commands ###
