"""add_rls_policies

Revision ID: 7b2f6ea50d81
Revises: fef856c068bf
Create Date: 2026-08-24 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b2f6ea50d81'
down_revision: Union[str, None] = 'fef856c068bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute('ALTER TABLE abuse_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE abuse_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON abuse_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE agent_memory_entries ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE agent_memory_entries FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON agent_memory_entries USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE agent_states ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE agent_states FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON agent_states USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE ai_audit_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE ai_audit_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON ai_audit_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE assets ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE assets FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON assets USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON audit_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE budget_rules ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE budget_rules FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON budget_rules USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE budgets ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE budgets FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON budgets USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE capability_ghosts ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE capability_ghosts FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON capability_ghosts USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE capability_haunt_states ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE capability_haunt_states FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON capability_haunt_states USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE chain_definitions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE chain_definitions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON chain_definitions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE chain_run_records ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE chain_run_records FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON chain_run_records USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE compliance_checks ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE compliance_checks FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON compliance_checks USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE content_filter_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE content_filter_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON content_filter_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE cost_allocations ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE cost_allocations FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON cost_allocations USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE cost_predictions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE cost_predictions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON cost_predictions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE decision_frames ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE decision_frames FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON decision_frames USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE deployments ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE deployments FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON deployments USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE execution_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE execution_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON execution_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE forecast_models ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE forecast_models FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON forecast_models USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE incident_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE incident_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON incident_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE invoices ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE invoices FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON invoices USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE kill_switch_states ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE kill_switch_states FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON kill_switch_states USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE model_configs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE model_configs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON model_configs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE notifications ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE notifications FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON notifications USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE orders ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE orders FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON orders USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE payments ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE payments FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON payments USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pgl_anchors ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_anchors FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pgl_anchors USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pipeline_runs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pipeline_runs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pipeline_runs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pipelines ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pipelines FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pipelines USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE playground_prompts ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE playground_prompts FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON playground_prompts USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE playground_sessions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE playground_sessions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON playground_sessions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pricing_billing_events ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pricing_billing_events FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pricing_billing_events USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE provider_decision_audit_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_decision_audit_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON provider_decision_audit_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE provider_keys ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_keys FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON provider_keys USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE provider_routing_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_routing_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON provider_routing_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE quarantined_intents ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE quarantined_intents FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON quarantined_intents USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE rag_agent_memory ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE rag_agent_memory FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON rag_agent_memory USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE rag_document_chunks ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE rag_document_chunks FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON rag_document_chunks USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE routing_decisions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE routing_decisions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON routing_decisions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE routing_policies ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE routing_policies FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON routing_policies USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE security_events ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE security_events FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON security_events USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE usage_metrics ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE usage_metrics FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON usage_metrics USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE veklom_agent_sessions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE veklom_agent_sessions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON veklom_agent_sessions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE veklom_runs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE veklom_runs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON veklom_runs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE vnp_claim_requests ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE vnp_claim_requests FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON vnp_claim_requests USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE vnp_stake_logs ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE vnp_stake_logs FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON vnp_stake_logs USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE wallet_transactions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON wallet_transactions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE workspace_integrations ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_integrations FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON workspace_integrations USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_members FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON workspace_members USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE workspace_provider_credentials ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_provider_credentials FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON workspace_provider_credentials USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pgl_certificates ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_certificates FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pgl_certificates USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE pgl_ledger_events ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_ledger_events FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON pgl_ledger_events USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON subscriptions USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE tier_upgrades ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE tier_upgrades FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON tier_upgrades USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE users ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE users FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON users USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE workspace_plugins ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_plugins FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON workspace_plugins USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE api_keys FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON api_keys USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")
    op.execute('ALTER TABLE execution_identities ENABLE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE execution_identities FORCE ROW LEVEL SECURITY')
    op.execute("CREATE POLICY tenant_isolation_policy ON execution_identities USING (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true)))) WITH CHECK (((current_setting('app.bypass_rls'::text, true) = 'on'::text) OR ((workspace_id)::text = current_setting('app.workspace_id'::text, true))))")

def downgrade() -> None:
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON abuse_logs')
    op.execute('ALTER TABLE abuse_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE abuse_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON agent_memory_entries')
    op.execute('ALTER TABLE agent_memory_entries NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE agent_memory_entries DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON agent_states')
    op.execute('ALTER TABLE agent_states NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE agent_states DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON ai_audit_logs')
    op.execute('ALTER TABLE ai_audit_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE ai_audit_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON assets')
    op.execute('ALTER TABLE assets NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE assets DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON audit_logs')
    op.execute('ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON budget_rules')
    op.execute('ALTER TABLE budget_rules NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE budget_rules DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON budgets')
    op.execute('ALTER TABLE budgets NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE budgets DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON capability_ghosts')
    op.execute('ALTER TABLE capability_ghosts NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE capability_ghosts DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON capability_haunt_states')
    op.execute('ALTER TABLE capability_haunt_states NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE capability_haunt_states DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON chain_definitions')
    op.execute('ALTER TABLE chain_definitions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE chain_definitions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON chain_run_records')
    op.execute('ALTER TABLE chain_run_records NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE chain_run_records DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON compliance_checks')
    op.execute('ALTER TABLE compliance_checks NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE compliance_checks DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON content_filter_logs')
    op.execute('ALTER TABLE content_filter_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE content_filter_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON cost_allocations')
    op.execute('ALTER TABLE cost_allocations NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE cost_allocations DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON cost_predictions')
    op.execute('ALTER TABLE cost_predictions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE cost_predictions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON decision_frames')
    op.execute('ALTER TABLE decision_frames NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE decision_frames DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON deployments')
    op.execute('ALTER TABLE deployments NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE deployments DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON execution_logs')
    op.execute('ALTER TABLE execution_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE execution_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON forecast_models')
    op.execute('ALTER TABLE forecast_models NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE forecast_models DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON incident_logs')
    op.execute('ALTER TABLE incident_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE incident_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON invoices')
    op.execute('ALTER TABLE invoices NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE invoices DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON kill_switch_states')
    op.execute('ALTER TABLE kill_switch_states NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE kill_switch_states DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON model_configs')
    op.execute('ALTER TABLE model_configs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE model_configs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON notifications')
    op.execute('ALTER TABLE notifications NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE notifications DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON orders')
    op.execute('ALTER TABLE orders NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE orders DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON payments')
    op.execute('ALTER TABLE payments NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE payments DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pgl_anchors')
    op.execute('ALTER TABLE pgl_anchors NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_anchors DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pipeline_runs')
    op.execute('ALTER TABLE pipeline_runs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pipeline_runs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pipelines')
    op.execute('ALTER TABLE pipelines NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pipelines DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON playground_prompts')
    op.execute('ALTER TABLE playground_prompts NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE playground_prompts DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON playground_sessions')
    op.execute('ALTER TABLE playground_sessions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE playground_sessions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pricing_billing_events')
    op.execute('ALTER TABLE pricing_billing_events NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pricing_billing_events DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON provider_decision_audit_logs')
    op.execute('ALTER TABLE provider_decision_audit_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_decision_audit_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON provider_keys')
    op.execute('ALTER TABLE provider_keys NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_keys DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON provider_routing_logs')
    op.execute('ALTER TABLE provider_routing_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE provider_routing_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON quarantined_intents')
    op.execute('ALTER TABLE quarantined_intents NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE quarantined_intents DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON rag_agent_memory')
    op.execute('ALTER TABLE rag_agent_memory NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE rag_agent_memory DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON rag_document_chunks')
    op.execute('ALTER TABLE rag_document_chunks NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE rag_document_chunks DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON routing_decisions')
    op.execute('ALTER TABLE routing_decisions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE routing_decisions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON routing_policies')
    op.execute('ALTER TABLE routing_policies NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE routing_policies DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON security_events')
    op.execute('ALTER TABLE security_events NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE security_events DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON usage_metrics')
    op.execute('ALTER TABLE usage_metrics NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE usage_metrics DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON veklom_agent_sessions')
    op.execute('ALTER TABLE veklom_agent_sessions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE veklom_agent_sessions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON veklom_runs')
    op.execute('ALTER TABLE veklom_runs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE veklom_runs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON vnp_claim_requests')
    op.execute('ALTER TABLE vnp_claim_requests NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE vnp_claim_requests DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON vnp_stake_logs')
    op.execute('ALTER TABLE vnp_stake_logs NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE vnp_stake_logs DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON wallet_transactions')
    op.execute('ALTER TABLE wallet_transactions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE wallet_transactions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON workspace_integrations')
    op.execute('ALTER TABLE workspace_integrations NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_integrations DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON workspace_members')
    op.execute('ALTER TABLE workspace_members NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_members DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON workspace_provider_credentials')
    op.execute('ALTER TABLE workspace_provider_credentials NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_provider_credentials DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pgl_certificates')
    op.execute('ALTER TABLE pgl_certificates NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_certificates DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON pgl_ledger_events')
    op.execute('ALTER TABLE pgl_ledger_events NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE pgl_ledger_events DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON subscriptions')
    op.execute('ALTER TABLE subscriptions NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON tier_upgrades')
    op.execute('ALTER TABLE tier_upgrades NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE tier_upgrades DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON users')
    op.execute('ALTER TABLE users NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE users DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON workspace_plugins')
    op.execute('ALTER TABLE workspace_plugins NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE workspace_plugins DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON api_keys')
    op.execute('ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation_policy ON execution_identities')
    op.execute('ALTER TABLE execution_identities NO FORCE ROW LEVEL SECURITY')
    op.execute('ALTER TABLE execution_identities DISABLE ROW LEVEL SECURITY')
