"""add missing columns

Revision ID: cb82d08a68fe
Revises: 25dabdc85714
Create Date: 2026-07-18 20:23:01.625092

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb82d08a68fe'
down_revision: Union[str, None] = '25dabdc85714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # capability_haunt_states was originally created via Base.metadata.create_all()
    # with no Alembic revision. This migration must create it if absent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'capability_haunt_states' not in existing_tables:
        op.create_table(
            'capability_haunt_states',
            sa.Column('id', sa.String(36), primary_key=True),
            sa.Column('workspace_id', sa.String(36), nullable=False, index=True),
            sa.Column('fingerprint', sa.String(255), nullable=False, unique=True, index=True),
            sa.Column('status', sa.String(32), server_default='idle'),
            sa.Column('heartbeat', sa.Integer(), server_default='0'),
            sa.Column('queued_revision', sa.Integer(), server_default='1'),
            sa.Column('freshest_artifact_revision', sa.Integer(), server_default='0'),
            sa.Column('manifest', sa.JSON(), nullable=True, server_default='{}'),
            sa.Column('verification_results', sa.JSON(), nullable=True, server_default='{}'),
            sa.Column('error_log', sa.Text(), server_default=''),
            sa.Column('created_at', sa.DateTime(timezone=True)),
            sa.Column('updated_at', sa.DateTime(timezone=True)),
        )
    else:
        existing_cols = [c['name'] for c in inspector.get_columns('capability_haunt_states')]
        if 'manifest' not in existing_cols:
            op.add_column('capability_haunt_states', sa.Column('manifest', sa.JSON(), nullable=True, server_default='{}'))

    if 'vnp_regional_telemetry' in existing_tables:
        existing_cols = [c['name'] for c in inspector.get_columns('vnp_regional_telemetry')]
        if 'provenance_hash' not in existing_cols:
            op.add_column('vnp_regional_telemetry', sa.Column('provenance_hash', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vnp_regional_telemetry', 'provenance_hash')
    op.drop_column('capability_haunt_states', 'manifest')
    # ### end Alembic commands ###
