"""
GitHub Actions Pipeline Export
Generate CI/CD workflow YAML from compiled pipeline.
Enable one-click deployment to production.

Generated for: veklom-byos-backend/backend/gpc/
"""

from typing import Optional, Dict, Any, List
from dataclasses import dataclass
from datetime import datetime
import json
import base64


@dataclass
class GitHubActionsWorkflow:
    """CI/CD workflow configuration."""
    pipeline_id: str
    pipeline_name: str
    python_code: str
    execution_order: List[str]
    execution_schedule: Optional[str] = None  # cron format
    deployment_env: str = "production"
    notify_on_failure: bool = True
    

def generate_github_workflow(
    workflow: GitHubActionsWorkflow,
    vault_secret_path: str = "gpc-pipelines"
) -> str:
    """
    Generate GitHub Actions workflow YAML.
    
    Features:
    - Compile on commit (verify syntax)
    - Run pipeline on schedule or manual trigger
    - Store compiled code as artifact
    - Send results to Veklom backend
    - Notify Slack on failure
    - Production safety: requires approval before deploy to main
    """
    
    yaml_content = f"""# Generated by Veklom GPC
# Pipeline: {workflow.pipeline_name}
# ID: {workflow.pipeline_id}
# Generated: {datetime.utcnow().isoformat()}

name: GPC Pipeline - {workflow.pipeline_name}

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
  
  # Schedule (if configured)
{_generate_schedule_trigger(workflow.execution_schedule)}
  
  # On push to main branch
  push:
    branches:
      - main

env:
  VEKLOM_API_URL: ${{{{ secrets.VEKLOM_API_URL }}}}
  PIPELINE_ID: {workflow.pipeline_id}
  PIPELINE_NAME: {workflow.pipeline_name}

jobs:
  # ========================================================================
  # STAGE 1: Validate & Compile
  # ========================================================================
  
  compile:
    name: Compile Pipeline
    runs-on: ubuntu-latest
    outputs:
      compilation_id: ${{{{ steps.compile.outputs.compilation_id }}}}
      node_count: ${{{{ steps.compile.outputs.node_count }}}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{{{ runner.os }}}}-pip-${{{{ hashFiles('**/requirements.txt') }}}}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic fastapi
      
      - name: Compile pipeline
        id: compile
        run: |
          python -c "
          import json
          # Call Veklom compile endpoint
          import urllib.request
          
          request = urllib.request.Request(
            url='${{{{ env.VEKLOM_API_URL }}}}/api/v1/gpc/compile',
            method='POST',
            headers={{
              'Content-Type': 'application/json',
              'Authorization': 'Bearer ${{{{ secrets.VEKLOM_API_TOKEN }}}}'
            }},
            data=json.dumps({{
              'pipeline_id': '${{{{ env.PIPELINE_ID }}}}',
              'tenant_id': '${{{{ secrets.VEKLOM_TENANT_ID }}}}'
            }}).encode()
          )
          
          try:
            with urllib.request.urlopen(request) as response:
              result = json.loads(response.read())
              if result['success']:
                print(f\"::set-output name=compilation_id::{result['node_count']}_{{\int(time.time())}}\")
                print(f\"::set-output name=node_count::{result['node_count']}\")
              else:
                print('::error::Compilation failed')
                exit(1)
          except Exception as e:
            print(f'::error::{{str(e)}}')
            exit(1)
          "
      
      - name: Store compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pipeline-${{{{ steps.compile.outputs.compilation_id }}}}
          path: |
            pipeline.py
            pipeline.json
          retention-days: 30


  # ========================================================================
  # STAGE 2: Test on Staging (Sample Data)
  # ========================================================================
  
  test-staging:
    name: Test on Staging
    needs: compile
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.environment == 'staging'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Test pipeline (sample data)
        run: |
          curl -X POST \\
            -H "Authorization: Bearer ${{{{ secrets.VEKLOM_API_TOKEN }}}}" \\
            -H "Content-Type: application/json" \\
            -d "{{
              'pipeline_id': '${{{{ env.PIPELINE_ID }}}}',
              'tenant_id': '${{{{ secrets.VEKLOM_TENANT_ID }}}}',
              'mode': 'sample'
            }}" \\
            "${{{{ env.VEKLOM_API_URL }}}}/api/v1/gpc/test"
          
          if [ $? -ne 0 ]; then
            echo "::error::Pipeline test failed"
            exit 1
          fi
      
      - name: Generate test report
        if: always()
        run: |
          echo "## Pipeline Test Report" >> $GITHUB_STEP_SUMMARY
          echo "- **Pipeline**: ${{{{ env.PIPELINE_NAME }}}}" >> $GITHUB_STEP_SUMMARY
          echo "- **Nodes**: ${{{{ needs.compile.outputs.node_count }}}}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: Passed ✅" >> $GITHUB_STEP_SUMMARY


  # ========================================================================
  # STAGE 3: Deploy to Production (Manual Approval)
  # ========================================================================
  
  deploy-production:
    name: Deploy to Production
    needs: [compile, test-staging]
    runs-on: ubuntu-latest
    environment:
      name: production
      # IMPORTANT: Requires manual approval in GitHub UI
    if: |
      github.ref == 'refs/heads/main' &&
      (github.event_name == 'push' || github.event.inputs.environment == 'production')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy pipeline to production
        run: |
          curl -X POST \\
            -H "Authorization: Bearer ${{{{ secrets.VEKLOM_API_TOKEN }}}}" \\
            -H "Content-Type: application/json" \\
            -d "{{
              'pipeline_id': '${{{{ env.PIPELINE_ID }}}}',
              'tenant_id': '${{{{ secrets.VEKLOM_TENANT_ID }}}}',
              'environment': 'production'
            }}" \\
            "${{{{ env.VEKLOM_API_URL }}}}/api/v1/gpc/deploy"
      
      - name: Notify Slack (success)
        uses: slackapi/slack-github-action@v1
        if: success()
        with:
          webhook-url: ${{{{ secrets.SLACK_WEBHOOK_DEPLOY }}}}
          payload: |
            {{
              "text": "✅ Pipeline deployed",
              "blocks": [
                {{
                  "type": "header",
                  "text": {{
                    "type": "plain_text",
                    "text": "✅ GPC Pipeline Deployed"
                  }}
                }},
                {{
                  "type": "section",
                  "fields": [
                    {{
                      "type": "mrkdwn",
                      "text": "*Pipeline:*\\n{workflow.pipeline_name}"
                    }},
                    {{
                      "type": "mrkdwn",
                      "text": "*Environment:*\\nProduction"
                    }},
                    {{
                      "type": "mrkdwn",
                      "text": "*Ref:*\\n${{{{ github.ref }}}}"
                    }},
                    {{
                      "type": "mrkdwn",
                      "text": "*Commit:*\\n<${{{{ github.server_url }}}}/${{{{ github.repository }}}}/commit/${{{{ github.sha }}}}|${{{{ github.sha }}}}>\\n"
                    }}
                  ]
                }}
              ]
            }}
      
      - name: Notify Slack (failure)
        uses: slackapi/slack-github-action@v1
        if: failure()
        with:
          webhook-url: ${{{{ secrets.SLACK_WEBHOOK_ALERTS }}}}
          payload: |
            {{
              "text": "❌ Pipeline deployment failed",
              "blocks": [
                {{
                  "type": "section",
                  "text": {{
                    "type": "mrkdwn",
                    "text": "❌ *Deployment Failed*\\nPipeline: {workflow.pipeline_name}\\nRun: <${{{{ github.server_url }}}}/${{{{ github.repository }}}}/actions/runs/${{{{ github.run_id }}}}|${{{{ github.run_id }}}}>\\n"
                  }}
                }}
              ]
            }}


  # ========================================================================
  # STAGE 4: Audit & Compliance
  # ========================================================================
  
  audit:
    name: Audit & Compliance Check
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Check Law 25 compliance
        run: |
          # Verify Quebec data residency policy
          curl -X GET \\
            -H "Authorization: Bearer ${{{{ secrets.VEKLOM_API_TOKEN }}}}" \\
            "${{{{ env.VEKLOM_API_URL }}}}/api/v1/gpc/audit?pipeline_id=${{{{ env.PIPELINE_ID }}}}&days=1"
      
      - name: Create deployment record
        run: |
          curl -X POST \\
            -H "Authorization: Bearer ${{{{ secrets.VEKLOM_API_TOKEN }}}}" \\
            -H "Content-Type: application/json" \\
            -d "{{
              'pipeline_id': '${{{{ env.PIPELINE_ID }}}}',
              'tenant_id': '${{{{ secrets.VEKLOM_TENANT_ID }}}}',
              'deployment_ref': '${{{{ github.ref }}}}',
              'deployment_sha': '${{{{ github.sha }}}}',
              'deployment_time': '$(date -Iseconds)'
            }}" \\
            "${{{{ env.VEKLOM_API_URL }}}}/api/v1/gpc/audit-log"
"""
    
    return yaml_content


def _generate_schedule_trigger(schedule: Optional[str]) -> str:
    """Generate schedule trigger YAML if schedule is set."""
    if not schedule:
        return "  # No schedule configured"
    
    # schedule should be cron format: "0 0 * * *" (daily at midnight)
    return f"""  schedule:
    # Run on schedule
    - cron: '{schedule}'
"""


class GitHubWorkflowExporter:
    """Export compiled pipeline to GitHub Actions workflow."""
    
    def __init__(self, github_token: str):
        self.github_token = github_token
    
    async def export_to_github(
        self,
        repo_owner: str,
        repo_name: str,
        workflow: GitHubActionsWorkflow,
        branch: str = "main"
    ) -> Dict[str, Any]:
        """
        Commit workflow YAML to user's GitHub repo.
        
        Args:
            repo_owner: GitHub username/org
            repo_name: Repository name
            workflow: Workflow configuration
            branch: Target branch (default main)
        
        Returns:
            Commit result with URL
        """
        import aiohttp
        
        # Generate workflow YAML
        workflow_yaml = generate_github_workflow(workflow)
        
        # Encode for GitHub API
        workflow_b64 = base64.b64encode(workflow_yaml.encode()).decode()
        
        # API endpoint: PUT /repos/{owner}/{repo}/contents/{path}
        api_url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/contents/.github/workflows/gpc-{workflow.pipeline_id}.yml"
        
        # Get current file SHA (for update)
        async with aiohttp.ClientSession() as session:
            # GET to retrieve current SHA
            async with session.get(
                api_url,
                headers={"Authorization": f"token {self.github_token}"}
            ) as resp:
                current_file = await resp.json() if resp.status == 200 else {}
            
            # PUT to create/update workflow file
            payload = {
                "message": f"GPC: Deploy pipeline {workflow.pipeline_name}",
                "content": workflow_b64,
                "branch": branch,
            }
            
            if "sha" in current_file:
                payload["sha"] = current_file["sha"]
            
            async with session.put(
                api_url,
                json=payload,
                headers={"Authorization": f"token {self.github_token}"}
            ) as resp:
                result = await resp.json()
        
        if resp.status in (201, 200):
            return {
                "status": "success",
                "commit_sha": result["commit"]["sha"],
                "workflow_url": f"https://github.com/{repo_owner}/{repo_name}/blob/{branch}/.github/workflows/gpc-{workflow.pipeline_id}.yml",
                "actions_url": f"https://github.com/{repo_owner}/{repo_name}/actions"
            }
        else:
            return {
                "status": "failed",
                "error": result.get("message", "Unknown error"),
                "workflow_url": None
            }


# ============================================================================
# FASTAPI ROUTE: Export to GitHub
# ============================================================================

# Add to gpc_routes.py:

@router.post("/export-github")
async def export_to_github(
    pipeline_id: str,
    repo_owner: str,
    repo_name: str,
    github_token: str,
    tenant_id: str = Depends(get_tenant_id),
    schedule: Optional[str] = None  # cron format
):
    """
    Export compiled pipeline as GitHub Actions workflow.
    
    Args:
        pipeline_id: Pipeline to export
        repo_owner: GitHub username/org
        repo_name: Repository name
        github_token: GitHub personal access token
        schedule: Optional cron schedule for execution
    
    Returns:
        Workflow export result with commit details
    """
    try:
        # Load and compile pipeline
        compiler = GPCCompiler()
        pipeline_graph = GPCPipelineGraph(
            pipeline_id=pipeline_id,
            tenant_id=tenant_id
        )
        
        compilation = compiler.compile(pipeline_graph)
        if not compilation.success:
            raise ValueError("Pipeline compilation failed")
        
        # Create workflow
        workflow = GitHubActionsWorkflow(
            pipeline_id=pipeline_id,
            pipeline_name=pipeline_graph.name or f"Pipeline {pipeline_id[:8]}",
            python_code=compilation.python_code,
            execution_order=compilation.execution_order,
            execution_schedule=schedule
        )
        
        # Export to GitHub
        exporter = GitHubWorkflowExporter(github_token)
        result = await exporter.export_to_github(
            repo_owner=repo_owner,
            repo_name=repo_name,
            workflow=workflow
        )
        
        if result["status"] == "success":
            logger.info(
                f"Pipeline exported to GitHub",
                extra={
                    "tenant_id": tenant_id,
                    "pipeline_id": pipeline_id,
                    "repo": f"{repo_owner}/{repo_name}"
                }
            )
        
        return result
    
    except Exception as e:
        logger.exception(f"GitHub export failed: {e}")
        return {
            "status": "failed",
            "error": str(e)
        }
