name: APIsec

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '24 14 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_APIsec_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    env:
      APISEC_USERNAME: ${{ secrets.APISEC_USERNAME }}
      APISEC_PASSWORD: ${{ secrets.APISEC_PASSWORD }}
      APISEC_PROJECT: ${{ secrets.APISEC_PROJECT }}
    steps:
      - name: APIsec scan
        if: env.APISEC_USERNAME != '' && env.APISEC_PASSWORD != '' && env.APISEC_PROJECT != ''
        uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
        with:
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          apisec-project: ${{ secrets.APISEC_PROJECT }}
          sarif-result-file: "apisec-results.sarif"
      - name: APIsec credentials are not configured
        if: env.APISEC_USERNAME == '' || env.APISEC_PASSWORD == '' || env.APISEC_PROJECT == ''
        run: echo "APIsec scan skipped because its repository credentials are not configured."
      - name: Import results
        if: env.APISEC_USERNAME != '' && env.APISEC_PASSWORD != '' && env.APISEC_PROJECT != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./apisec-results.sarif
